INSERT INTO PIOTR.COURSE (ID, ADDRESSOFRUNOFFICE, CITYOFCOURS, CITYOFRUNOFFICE, CLIMB, DATEOFSTART, DESCENT, DISTANCE, EMAIL, INFO, "NAME", PAYMENTREQUIRED, PHONE, RUNNERSLIMIT, SHORTNAME, VERSION, ID_ORGANISER) 
	VALUES (1000, NULL, 'Płock', NULL, 0, 2018-08-31 23:00:00.0, 0, 44.0, NULL, NULL, 'BIEG Nocny 44', 0, NULL, 3, 'Bieg44', 1, 320);

